### ISSUE TITLE
Armor Potency and Reslilent Runes Not Working

### ISSUE THREAD

**Issue by NhojDev** [wanderers-guide/wanderers-guide#100]
### **Describe the bug**

Armor Potency runes doesn't increase total AC, they basically do nothing. While Resiliency runes both increase the AC and the Saves.

### **To Reproduce**

1. Get Any Armor.
2. Add Potency Rune to see no AC increase.
3. Remove Potency Rune.
4. Add Resiliency to see AC and Save increase.

### **Expected behavior**

Armor Potency should increase AC total. Resiliency Runes should only increase Saves. 

### **Screenshots**
Initial AC
![image](https://github.com/wanderers-guide/wanderers-guide/assets/98851780/c3fb6552-28e6-4ff8-a2be-92928c4e2237) 
Adding Potency Rune on Armor.
![image](https://github.com/wanderers-guide/wanderers-guide/assets/98851780/b7204f2f-af11-4c6d-8fba-0ceea6ed85bb)
No Change
![image](https://github.com/wanderers-guide/wanderers-guide/assets/98851780/3b84bb3c-b432-4b79-ba24-bc0659ecb5ed)

--------------------------------------------------------------------------------------------------------------------------------

Initial AC
![image](https://github.com/wanderers-guide/wanderers-guide/assets/98851780/ecf7f250-6e3f-449c-bfba-bd503add2629)

Adding Resiliency Rune.
![image](https://github.com/wanderers-guide/wanderers-guide/assets/98851780/c93b477c-a1d0-4af2-974f-7ab5d6cdf195)

Increase to Saves, but also AC.
![image](https://github.com/wanderers-guide/wanderers-guide/assets/98851780/1a85a00e-60be-402b-bef4-d250b14a20b6)

### **Desktop (please complete the following information):**

- OS: Windows
- Browser: Firefox
- Version: Latest

**Comment by Quzzar** [comment]
Should be working correctly now

**Comment by NemeiaStarag** [comment]
This behaviour doesn't seem to have changed. While I'm not super familiar with the project's codebase, I believe that there needs to be a change made around here to switch the AC bonus from being granted by resilient runes to potency runes:
https://github.com/wanderers-guide/wanderers-guide/blob/3222480db36e4dafe9004e225b7b905443d353cb/frontend/src/pages/character_sheet/sections/ArmorSection.tsx#L45C1-L60C4
