### ISSUE TITLE
Skills granted from Int increases not progressing correctly

### ISSUE THREAD

**Issue by tessellizard** [wanderers-guide/wanderers-guide#104]
### **Describe the bug**

Deception, Diplomacy, Medicine and Thievery skill upgrades replacing instead of combining with skill picks from the Investigator class.

### **To Reproduce**

1. Import the attached character file: [test-copy.json](https://github.com/user-attachments/files/15905409/test-copy.json)
2. Select Diplomacy for any of the level 2-5 skill increases.
3. Diplomacy stays at +7/Trained, the Timeline view changes from Diplomacy becoming Trained as a class pick to becoming Trained as a result of the selected skill increase.

### **Expected behavior**

Diplomacy increasing to +9/Expert, Timeline reflecting both skill increases.

### **Screenshots**
Initial timeline state:
![image](https://github.com/wanderers-guide/wanderers-guide/assets/10777102/d587ec55-065c-4e48-bdbe-ae87d8bf6ecd)

Final timeline state:
![image](https://github.com/wanderers-guide/wanderers-guide/assets/10777102/08709f66-0d95-4814-ab6b-bbfe3aa94d05)

### **Desktop (please complete the following information):**

- OS: Windows 11 Pro
- Browser: Chrome
- Version 125.0.6422.142

### **Additional context**

Probably something specific to this configuration, as Demetri could not reproduce this with a different Investigator build.  Originally encountered on a higher-level version of this character, where Nature and Performance (added as Investigator class picks from Int increases at higher levels, so possible sequencing issues there) were also affected.

**Comment by tessellizard** [comment]
On further testing, it looks like the issue is not those specific skills, but skills in class training slots added from Int boosts. Probably related to https://github.com/wanderers-guide/wanderers-guide/issues/51.

**Comment by tessellizard** [comment]
Not specific to Investigator either, I was able to reproduce this on a Witch character.

**Comment by a-hodges** [comment]
@Quzzar Request to move this issue to a high priority queue if possible.

**Comment by a-hodges** [comment]
I may have found the issue. Skills added via int boosts are executed later in the process than the skill boost class features since they rely on the attribute increase class features. Since they're executed after class features are executed and only set the skill to trained they have no effect if you increase the skill later since it's already trained.

**Comment by Quzzar** [comment]
This issue seems to be fixed now. Profs are now compiled on display rather than as operations execution.
