### ISSUE TITLE
'Search Everything' function broken

### ISSUE THREAD

**Issue by NemeiaStarag** [wanderers-guide/wanderers-guide#108]
### **Describe the bug**

The 'Search Everything' function is broken. Trying to use it causes it to load indefinitely and generates an error popup behind it. The popup reads "Failed to query collection: Internal Server Error".

### **To Reproduce**

1. Go to the site
2. Click on 'Search Everything'
3. Enter a search query
4. To see the error popup, exit the search

### **Expected behavior**

The search returns results based in the inputted query

### **Screenshots**

<img width="365" alt="An error message reading 'Failed to query collection: Internal Server Error'" src="https://github.com/user-attachments/assets/d86ddc49-b1de-455b-bca2-c7a6325cd41c">

### **Desktop**

- OS: macOS 12.7.5
- Browser Firefox
- Version 127.0.2

**Comment by Quzzar** [comment]
Fixed!
