### ISSUE TITLE
500 error when creating a lore skill

### ISSUE THREAD

**Issue by evoliee** [wanderers-guide/wanderers-guide#110]
### **Describe the bug**

Getting a 500 error when trying to set the proficiency of a new lore skill. 

### **To Reproduce**

1. Go to ‘home brew to create or edit a background (for me it’s when editing the only background in my pack Dice Dragon Games).
2. Create value
3. Hit T for proficiency without having named it.

### **Expected behavior**

Select proficiency level or give me an error telling me to name it first.

### **Screenshots**

![IMG_1577](https://github.com/user-attachments/assets/35cd1160-cc9c-4fa4-ba01-4b2badd559fc)

getting this error when hitting the back button. I assume it can’t set a proficiency for a value that doesn’t have a name. Would personally expect either a “give me a name first” required warning, or a dummy name until it’s set.

### **Smartphone (please complete the following information):**

- Device: iPad Air 5th gen
- OS: 17.5.1
- Browser: safari
- Version: unknown

### **Additional context**

Happened in my homebrew pack “[V] Dice Dragon Games”. Password should be “Cheesecake”. On the Enforcer background.

**Comment by Quzzar** [comment]
Seems to have been an issue with the background's operations. I structured the background to match the other backgrounds and it seems to work fine now!
