### ISSUE TITLE
Armor Runes Not Applying Correctly

### ISSUE THREAD

**Issue by LilithSyn** [wanderers-guide/wanderers-guide#112]
### **Describe the bug**

Armor Potency Runes are not applying AC bonus. Also, Resilient Runes are adding AC bonus in addition to saving throw.

### **To Reproduce**

1. Go to armor item in inventory
2. Click on Edit
3. Scroll down to Runes
4. Add a +1 Potency Rune to Potency Rune field and/or add a Armor Potency (+1) to the Property Runes field
5. Go to the AC section of the Health, Attributes, Saves page of the character sheet
6. Notice the AC does not show the bonus from the Potency Rune.

### **Expected behavior**

Expecting +1-3 AC values depending on the Potency Rune added.

### **Screenshots**

![Screenshot_20240724-184944](https://github.com/user-attachments/assets/20f0b7d2-515a-4d9a-8942-ff2127c02437)
![Screenshot_20240724-185020](https://github.com/user-attachments/assets/36ed6513-72a6-45eb-9bf0-f5c385b65eaf)
![Screenshot_20240724-190803](https://github.com/user-attachments/assets/3493a6b8-de49-46a8-bb86-90f95f2fb63c)
![Screenshot_20240724-190853](https://github.com/user-attachments/assets/1ade5c22-4372-4c2e-b788-5c330d936723)

### **Smartphone (please complete the following information):**

- Device: Motorola 5g Ace
- OS: Android
- Browser Chrome

### **Additional context**

Conversation starting on https://discord.com/channels/735260060682289254/944004628696141854/1262412332500390040

**Comment by NemeiaStarag** [comment]
I believe that there needs to be a change made around here to switch the AC bonus from being granted by resilient runes to potency runes:
https://github.com/wanderers-guide/wanderers-guide/blob/3222480db36e4dafe9004e225b7b905443d353cb/frontend/src/pages/character_sheet/sections/ArmorSection.tsx#L45C1-L60C4

**Comment by Quzzar** [comment]
Thanks for the detailed report! It's been fixed
