### ISSUE TITLE
Add HP editor modal

### ISSUE THREAD

**Issue by a-hodges** [wanderers-guide/wanderers-guide#119]
### **Is your feature request related to a problem? Please describe.**

Manually calculating HP changes is finicky and slow.

### **Describe the solution you'd like**

A modal dialogue to add or subtract HP (ideally taking temp hp first) would be very convenient.

### **Describe alternatives you've considered**

The primary alternative is having the editor tools always visible rather than in a modal, but that takes up excessive space, especially on smaller screens.

**Comment by VytorCalixto** [comment]
You can type math expressions in the HP input and it'll be automatically calculated after pressing Enter or clicking outside the HP field.

But I do agree that something to remove the temp HP first would be nice

**Comment by a-hodges** [comment]
Might be good to make that feature more obvious, but I have no idea how to do that.
