### ISSUE TITLE
Manage items with spells (staves, wands, etc)

### ISSUE THREAD

**Issue by VytorCalixto** [wanderers-guide/wanderers-guide#153]
### **Is your feature request related to a problem? Please describe.**

I want a way to manage staff charges and wand uses, preferably in the spells tab.

### **Describe the solution you'd like**

The staff manager should consider whether the character is a prepared or spontaneous caster to give them the correct number of charges and how to cast spells from the staff. Wands should show if another cast would overcharge them.

When you cast a spell from a staff, the correct number of charges should be spent.

In the spells tab, there should be an entry for the staff/wand with the spells the item has. Wands may be its own accordion group since characters can accumulate a lot of wands, and adding an accordion for a single spell might take up too much space.

When you take a rest the system should prompt you to reset the wand casts and replenish the staff charges automatically.

### **Describe alternatives you've considered**

Those items could add custom spellcasting operations to mimic those effects, but they lead to constant tinkering and editing of the item to replicate the feature.

### **Additional context**

Characters with dual classes or archetypes that give them spontaneous and prepared spellcasting might impose a greater challenge on the staff manager. Maybe the staff manager has a toggle to determine if they are prepared or spontaneous.

**Comment by Quzzar** [comment]
Started working on this. See `manage-staves-and-wands_issue-153` branch
