### ISSUE TITLE
Unable to Equip Blunderbuss

### ISSUE THREAD

**Issue by zac-just-zac** [wanderers-guide/wanderers-guide#155]
### **Describe the bug**

The Blunderbuss cannot be equipped on the inventory page. Appears to not be properly a weapon as the details are missing attack bonus and damage fields. However under [Edit Item > Misc. Sections > Weapons] the information is all correct.

### **To Reproduce**

1. Create Character
2. Add Blunderbuss to inventory

### **Expected behavior**

Other weapons I checked are able to be equipped in order to appear in the Weapon Attacks section. They also display attack bonus and damage information.

### **Screenshots**

<img width="998" alt="image" src="https://github.com/user-attachments/assets/4c870cc6-5feb-440a-a295-c35d596a3093">

<img width="435" alt="image" src="https://github.com/user-attachments/assets/496ef232-2db5-41d9-b2f7-de2806224d12">

<img width="425" alt="image" src="https://github.com/user-attachments/assets/4a86e39c-d2b0-4c77-9a25-f2f81f9f2e54">

<img width="442" alt="image" src="https://github.com/user-attachments/assets/4ec2072f-060e-4ed3-8b4d-073bf0389a32">

### **Desktop (please complete the following information):**

- OS: macOS Sonoma 14.7
- Browser: Safari 18.0
- Version: ? (accessed 9/26/24 around 2pm EDT)

### **Additional context**

I originally noticed this issue on a character imported from Pathbuilder 2e JSON ID. The character is an Inventor and the blunderbuss is his weapon innovation. I thought this might be the source of my issue, however it appeared on a fresh character as well.

**Comment by Quzzar** [comment]
Issue appears to be fixed. Likely a content data issue.
