### ISSUE TITLE
No Longer Able to Add Operations to Source

### ISSUE THREAD

**Issue by LilithSyn** [wanderers-guide/wanderers-guide#160]
### **Describe the bug**

When attempting to add an operation to a source book, instead of the pop-up Operations window showing in front of the Update Content Source window, it is showing in the background an inaccessible.

### **To Reproduce**

1. Go to 'Open Source Info' (i.e. from Dark Archive or Rage of Elements)
2. Click on 'Something Wrong'
3. Click on 'Submit Content Update'
4. Scroll down to 'Operations' and click on it.
5. See error of separate pop-up Operations window showing behind the Update Content Source window as inaccessible.

### **Expected behavior**

Pop-up Operations window should be in front of the Update Content Source window, or able to be clicked into for editing.

### **Screenshots**

![image](https://github.com/user-attachments/assets/6f92813b-bb39-443a-ad82-b0c0fb0eec6b)

### **Smartphone (please complete the following information):**

- Device: Desktop
- OS: Windows 11 Home
- Browser: Chrome
- Version: 24H2

### **Additional context**

Initially observed on https://discord.com/channels/735260060682289254/1230609832382435398/1306312314395299972

Once bug is fixed, I will need to submit content updates to:
Rage of Elements: Inject into Selection (Domains | Select a Domain) the Metal entry per https://2e.aonprd.com/Domains.aspx?ID=62
Dark Archive: Inject into Selection (Patrons | Select a Patron) the Pact entry per https://2e.aonprd.com/Patrons.aspx?ID=11

**Comment by Quzzar** [comment]
Fixed! Thanks for the great report :)
