### ISSUE TITLE
Dockerize WG

### ISSUE THREAD

**Issue by Quzzar** [wanderers-guide/wanderers-guide#31]
**Is your feature request related to a problem? Please describe.**
Setting up WG currently requires some frontend setup and configuring access to Supabase, which can be streamlined. It also means we'll be working with the production database directly in development - which is never a good idea.

**Describe the solution you'd like**
Introduce Docker support to simplify the setup process and allow easily running the database and edge functions locally. Will need to create a docker-compose.yml file and setup the frontend, edge functions, and database.

_Frontend:_
Should be fairly easy, just run `npm i` and `npm run dev`

_Edge Functions:_
See https://supabase.com/docs/guides/functions/quickstart#running-edge-functions-locally

_Database:_
See https://supabase.com/docs/guides/cli/local-development

**Describe alternatives you've considered**
We don't need to use Docker for this, we could get away with running all of these services manually. We also could create a development version of the database on Supabase, but these are still not great solutions that will still take a while to configure. It's best to do this right the first time.

**Additional context**
None

**Comment by fezproof** [comment]
Not sure if we need to dockerise the frontend as our hosting has nothing to do with Docker. All we need to do is support the local version of supabase (which already uses docker) and add the cuorrect urls to the env. See https://supabase.com/docs/guides/cli/getting-started
Looks like the only thing missing is the seed.sql needing some data.

**Comment by RandomLegend** [comment]
I stumbled across this and found that @Quzzar closed this as completed, but as far as i can see this is not completed?

Are there plans to provide a simple docker-compose to have everything automated and contained so we could spin this up easily?
