### ISSUE TITLE
Skill proficiencies from Int modifier don't get added

### ISSUE THREAD

**Issue by Moviment0** [wanderers-guide/wanderers-guide#51]
### **Describe the bug**

The additional skill proficiencies a character get's based on their Int modifier don't get added properly. The selected skills don't actually become trained, so you can even select them multiple times without actually getting the proficiency.

### **To Reproduce**

1. Make a character with at least +1 Int
2. Select skills in the class tab
3. The last 1-4 skills (based on Int mod) don't get trained proficiency

### **Expected behavior**

Properly add proficinencies

### **Screenshots**

<img width="377" alt="Picture1" src="https://github.com/wanderers-guide/wanderers-guide/assets/134845284/da24619c-6b12-4999-b832-906cb1db9bb3">

### **Desktop (please complete the following information):**

- OS: Windows
- Browser: Brave

**Comment by Moviment0** [comment]
I just noticed the same problem for the additional languages based on Int mod:
![image](https://github.com/wanderers-guide/wanderers-guide/assets/134845284/8d403b16-48ca-4973-883a-959111168a7a)

**Comment by Quzzar** [comment]
Fixed
