### ISSUE TITLE
Sickle is missing the "trip" property

### ISSUE THREAD

**Issue by Moviment0** [wanderers-guide/wanderers-guide#52]
https://2e.aonprd.com/Weapons.aspx?ID=364

**Comment by VytorCalixto** [comment]
@Quzzar Think I found the bug. The `trip`  trait has its content source set as the Bestiary instead of the Monster Core

**Comment by Moviment0** [comment]
shouldn't the source be the player core, since it's a weapon from there?
https://2e.aonprd.com/Traits.aspx?ID=716

**Comment by VytorCalixto** [comment]
The `Sickle` has the correct content source, but the `Trip` trait hasn't. Honestly I don't think it would make a difference to change it to the `Monster Core` source or `Player Core`, but `Player Core` is the best option for a weapon trait.

**Comment by Quzzar** [comment]
Good catch @VytorCalixto @Moviment0 
Changed the trip trait's source to be from the Player Core and it fixed it

**Comment by Quzzar** [comment]
In general, I think we ought to generally go with putting traits in the Player Core when it's debatable. The Player Core is a required source for most other books, while the Monster Core isn't.
