### ISSUE TITLE
Selected hex focus spell doesn't get added properly

### ISSUE THREAD

**Issue by Moviment0** [wanderers-guide/wanderers-guide#54]
### **Describe the bug**

The hex focus spell you can choose for the witch at level 1 doesn't show up on the character page.

### **Screenshots**

<img width="584" alt="2024-04-18_13-06" src="https://github.com/wanderers-guide/wanderers-guide/assets/134845284/bd0fb480-7825-4950-bb73-614160188b1b">
<img width="568" alt="2024-04-18_13-08" src="https://github.com/wanderers-guide/wanderers-guide/assets/134845284/eee2eb28-f71c-4c43-b93a-2c102b485085">

**Comment by Quzzar** [comment]
Fixed
