### ISSUE TITLE
Cannot select druidic order

### ISSUE THREAD

**Issue by silentnoodlemaster** [wanderers-guide/wanderers-guide#55]
### **Describe the bug**
When selecting a druidic order, an error appears about the order skill `Invalid adjust amount for prof: SKILL_INTIMIDATION, 0`  

### **Screenshots**
![image](https://github.com/wanderers-guide/wanderers-guide/assets/10667809/058c01a3-b890-49d7-9fc1-796b16b904b9)

### **Desktop (please complete the following information):**

- OS: Linux
- Browser: Firefox
- Version 125

### **Additional context**

character https://wanderersguide.app/sheet/1111

**Comment by Quzzar** [comment]
Fixed
