### ISSUE TITLE
Voluntary Ability Flaw Produces Bugged Scores

### ISSUE THREAD

**Issue by empty79-2** [wanderers-guide/wanderers-guide#58]
### **Describe the bug**

When you activate the Voluntary Flaw variante rule and select a voluntary score, instead of one being subtracted from the score the number becomes a very big negative one (usually smaller than -100)

### **To Reproduce**

1. Make a character
2. Activate the Voluntary Flaw variante rule under "Options"
3. Go to Builder
4. Select a voluntary flaw.

### **Expected behavior**

The number for the selected score grows extremely low (Usually less than -100) and the display bugs out

### **Desktop (please complete the following information):**

-Happens both on Linux Ubuntu & Windows 10

### **Additional context**

My personal guess would be that maybe the -1 of the voluntary flaw gets applied repeatedly. But this is just a semi-educated guess.
Here is a link to a character where I reproduced the problem: https://wanderersguide.app/sheet/1432

**Comment by Quzzar** [comment]
Fixed
