### ISSUE TITLE
Renaming Created (Proficiency) Value Disables Proficiency Selection

### ISSUE THREAD

**Issue by empty79-2** [wanderers-guide/wanderers-guide#59]
### **Describe the bug**

When creating a custom proficiency value, giving yourself "trained" proficiency and then renaming the value, the selection menus, where you had that skill selected to be trained, will bug out.

Under the "Initial Stats" Section it will display "Select an Option" instead of "Select a Skill to be trained". When clicking it there will be no options listed.

In the Skill upgrade section (At level 3 for example) there field where you can select skills to upgrade will disappear alltogether.

### **To Reproduce**

1. Create a character
2. In the "Options" section, enable "Custom Operations"
3. Use "Create Value" to create a proficiency
4. (Maybe: Set the "ATTRIBUTE_INT". This most likely has nothing to do with the bug, but I just now noticed that I coincidently tested it wilt INT both times).
5. Set your level to lv 4 (Lv 3 should also work)
6. Go to "Builder"
7. Select the custom skill as a trained skill in the "Initial Stats" Section
8. Upgrade the custom skill to expert on lv 3
9. Go back to "Home" and change the name of the custom variable
10. Go back to "Builder" and try to change the fields where you previously selected your custom skills

### **Expected behavior**

Under the "Initial Stats" Section it will display "Select an Option" instead of "Select a Skill to be trained". When clicking it there will be no options listed.

In the Skill upgrade section (At level 3 for example) there field where you can select skills to upgrade will disappear alltogether.

### **Desktop (please complete the following information):**

- Happend both an Windows 10 and Ubuntu

### **Additional context**

Here is a character where I reproduced the error: https://wanderersguide.app/sheet/1444

**Comment by Quzzar** [comment]
Fixed
