### ISSUE TITLE
Non-multiclass archetype feats dont show up in the archetype menu

### ISSUE THREAD

**Issue by Agentblax** [wanderers-guide/wanderers-guide#62]
### **To Reproduce**

1. With Dark Archive enabled, pick sleepwalker dedication at level 4
2. Attempt to pick a level 6 class feat
3. Swap to the "Archetype Feats" submenu
4. See an menu with "*No feats found!*".

### **Expected behavior**

I expected to see archetype feats such as Vision of foresight, a level 6 sleepwalker feat.

### **Screenshots**

![image](https://github.com/wanderers-guide/wanderers-guide/assets/83842531/1087cde6-488f-4339-8c22-ddf3e7b4ba79)
![image](https://github.com/wanderers-guide/wanderers-guide/assets/83842531/fdc1f787-2970-4de1-8ed9-ca610da80b44)
![image](https://github.com/wanderers-guide/wanderers-guide/assets/83842531/26f0efcc-4b93-45ef-9311-3e0e1976108b)
![image](https://github.com/wanderers-guide/wanderers-guide/assets/83842531/3cce0357-7910-4b48-9707-112ddd844020)
![image](https://github.com/wanderers-guide/wanderers-guide/assets/83842531/fe486ce5-e082-4a1e-964e-c98af4a7cfea)
![image](https://github.com/wanderers-guide/wanderers-guide/assets/83842531/16d9b22f-7bea-4ff0-813b-511666f1c1ee)

### **Desktop (please complete the following information):**

- OS: Windows
- Browser Firefox 
- 
### **Additional Context**
I've attempted the same thing with acrobat and archer dedications, which also didnt work. Bard dedication however did. I also attempted to pick dedications in both class and Free Archetype slots, as well as trying both slots for archetype feats afterwards.

**Comment by a-hodges** [comment]
@Quzzar Request to close. This is a content issue, not a code issue.
