### ISSUE TITLE
500 Error when trying to select spells

### ISSUE THREAD

**Issue by MikaelaIrish** [wanderers-guide/wanderers-guide#73]
### **Describe the bug**

In the character sheet view, the manage spells dialogue comes up correctly, but pressing any of the add spell buttons causes it to go to a 500 error screen.

### **To Reproduce**

1. Go to a character sheet
2. Click on manage spells
3. Click any 'select spell' button

### **Expected behavior**

I would expect a spell picker to appear so I can select spells.

### **Screenshots**

![image](https://github.com/wanderers-guide/wanderers-guide/assets/703295/95ce9f24-2129-44a6-a96d-c0b0d52bd5c1)
![image](https://github.com/wanderers-guide/wanderers-guide/assets/703295/7d0d40f2-2b7f-4759-940b-0023f168f5c8)

### **Desktop (please complete the following information):**

- OS: Windows 11
- Browser Chrome
- Version 123.0.6312.86

### **Additional context**

Tried with both Druid and Wizard classes

**Comment by VytorCalixto** [comment]
@Quzzar This is fixed in #72. I can open a PR with just the bugfix if it's better

**Comment by MikaelaIrish** [comment]
No worries!  Just didn't see the bug listed otherwise, and it seems pretty core functionality.

**Comment by VytorCalixto** [comment]
@MikaelaIrish thanks for reporting!
