### ISSUE TITLE
not finding content with apostrophe with search

### ISSUE THREAD

**Issue by silentnoodlemaster** [wanderers-guide/wanderers-guide#75]
Searching "You're Next" does not return the rogue feat by that name even though it exists. Assuming the apostrophe is relevant, might not be.

![image](https://github.com/wanderers-guide/wanderers-guide/assets/10667809/371c1e33-de16-4abe-ba29-1ae9276681b8)

**Comment by silentnoodlemaster** [comment]
oh yeah, also tried a bunch of variations like "Youre Next" and "You re next" but none showed the actual feat

**Comment by Quzzar** [comment]
Fixed!
