### ISSUE TITLE
Homebrew appearing in 

### ISSUE THREAD

**Issue by NemeiaStarag** [wanderers-guide/wanderers-guide#82]
### **Describe the bug**

When using the 'Search everything' feature, entries from published homebrew packages appear, without the user being subscribed to them or having access. 

### **To Reproduce**

I was unable to reproduce this behaviour at the time of submitting this report, but these are the steps that I remember working.

1. Go to the Wanderer's Guide homepage
2. Click on the 'Search everything' button
3. Search for an entry from a homebrew bundle, or view a class to see homebrew features appearing under it.
4. The homebrew content should be visible, whether or not the user is subscribed or has access to it.

### **Expected behavior**

Either homebrew content never appears in the search, or only content from subscribed bundles appears.

### **Desktop (please complete the following information):**

- OS: macOS 12.7.4
- Browser: Firefox
- Version: 125.0.3 (64-bit)

### **Additional context**

- Discord user bluesabere also encountered this issue.
- The only bundle that content has been seen from is the locked 'Pathfinder with the bois' bundle.

**Comment by Quzzar** [comment]
Fixed!
