### ISSUE TITLE
Lower Rank Spells cannot be add as higher level versions in bard

### ISSUE THREAD

**Issue by Dharkov** [wanderers-guide/wanderers-guide#93]
### **Describe the bug**

When a spell that can be added as a higher level rank than its base rank is added, It is always added as the minimum rank for the spell in the bard sheet. 

### **To Reproduce**

Steps to reproduce the behaviour:

1. Create a bard with higher than 1st ranks spells
2. Go to manage spells and add a spell hightent as a higher rank than its base rank. The spell is added to the list of possible spells. 
3. Go to the spells area. 
4. The spell is added as the minimum rank, even if multiple spells of the same spell are added in different ranks that all appear as copies. 

### **Expected behavior**

The spells should appear in different ranks able to be cast as different levels 

### **Screenshots**

![image](https://github.com/wanderers-guide/wanderers-guide/assets/171644023/c0eb7ccb-a8e7-4259-adee-a97649719122)
![image2](https://github.com/wanderers-guide/wanderers-guide/assets/171644023/71757329-b394-41a6-8125-6663d953ae86)
![image3](https://github.com/wanderers-guide/wanderers-guide/assets/171644023/f75a0379-a180-447a-bca7-53d9e1da48dd)

### **Desktop (please complete the following information):**

- OS: Windows 11
- Browser: chrome
- Version 125.0.6422.114

**Comment by Quzzar** [comment]
Fixed!
