### ISSUE TITLE
Incorrect handling of bulk according to Game Rules

### ISSUE THREAD

**Issue by Dharkov** [wanderers-guide/wanderers-guide#94]
### **Is your feature request related to a problem? Please describe.**

The current system handles light bulk (L) items as 0.1 bulk. However, the game rules consider L as nothing until they add up to 10 since it does not account for decimals. This creates the problem of characters being encumbered when they are just 1 Light bulk over their limit.

### **Describe the solution you'd like**

Bulk should always be rounded down for the purpose of assigning the encumbered condition. The decimal numbers are useful to track how close to the next round bulk number you are. 

### **Describe alternatives you've considered**

The simple solution could create some confusion since it would seem like is not considering bulk correctly. The best solution is to display bulk as whole numbers, and the number of L items over the whole number Ex: 5 bulk and 8L / Bulk: 5(8L) 

### **Additional context**

Right now characters are being penalized incorrectly and making bulk rules more harsh.

**Comment by Quzzar** [comment]
Fixed!
