### ISSUE TITLE
Spells added through Caster sublist get added to all lists

### ISSUE THREAD

**Issue by Neophewl** [wanderers-guide/wanderers-guide#96]
### **Describe the bug**

Spells added through Caster sublist get added to Focus and Ritual Lists. The spells will show up on the main spells tab, but not in the sublist for rituals. The only way to take them off the Ritual / Focus list is to remove them from the main caster sublist.

### **To Reproduce**

1. Go to spells tab
2. Scroll to Bard / Witch / Wizard Spell
3. Click Manage
4. Add spell to list (left list for Witch / Wizard)
5. Spell is now added to Focus and Ritual List in Spells Tab
6. Click Manage on Ritual List
7. Spell is not shown in list and can only be deleted from man spell list

### **Expected behavior**

Spells added to main caster list should not get added to Focus and Ritual Lists

### **Screenshots**
Daze was added to bard List, but also shows up in focus list

![image](https://github.com/wanderers-guide/wanderers-guide/assets/121769494/ef6a4ec0-7967-42fb-af48-64632014a521)

All spells showing up in Ritual List
![image](https://github.com/wanderers-guide/wanderers-guide/assets/121769494/480b1474-19a0-4b82-a7ec-28959dc804fb)

Spells not in Ritual Managed sublist
![image](https://github.com/wanderers-guide/wanderers-guide/assets/121769494/cb0f4d1a-eec3-4cd3-bbf0-af2a6d5c81c4)

### **Desktop (please complete the following information):**

- OS: Windows 11
- Browser Chrome and Firefox

### **Smartphone (please complete the following information):**

Not Tested

**Comment by Quzzar** [comment]
Fixed!
